fail_fast: true
repos:
    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
          - id: black
            exclude: (pre-commit|docs)/(.*)
    - repo: https://github.com/pycqa/isort
      rev: 6.0.1
      hooks:
        - id: isort
    - repo: https://github.com/myint/rstcheck
      rev: v6.2.5
      hooks:
          - id: rstcheck
            name: rstcheck
            entry: rstcheck --ignore-messages "Duplicate explicit target name"
            language: python
            types: [rst]
    - repo: https://github.com/collective/zpretty
      rev: 3.1.1
      hooks:
          - id: zpretty
            name: zpretty
